[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v4-core/=lib/v4-core/",
    "solmate/=lib/solmate/",
]
gas_limit = 3000000000
gas_reports = ["*"]

via_ir = true
optimizer = true
optimizer_runs = 200

evm_version = "cancun"

# disable warnings about unused local variables and unused parameters
ignored_error_codes = ["unused-var", "unused-param", "shadowing"]


#[dependencies]
# OpenZeppelin Contracts
#"OpenZeppelin/openzeppelin-contracts" = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v4.9.3" }

# Solmate
#transmissions11/solmate" = { git = "https://github.com/transmissions11/solmate.git", tag = "v6.0.0" }

# Uniswap V4 core & periphery
#"Uniswap/v4-core"      = { git = "https://github.com/Uniswap/v4-core.git",      branch = "main" }
#"Uniswap/v4-periphery" = { git = "https://github.com/Uniswap/v4-periphery.git", branch = "main" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
